name: crosscompile_maxima32

on: [push]

env:
  BUILD_TYPE: Release

permissions:
  contents: read

jobs:
  compile_latest:
    runs-on: ubuntu-latest

    steps:
      - name: install_packages
        run: |
             sudo dpkg --add-architecture i386
             sudo apt-get update
             sudo apt-get -y upgrade
             sudo apt-get install g++-mingw-w64-i686 gcc-mingw-w64-i686 cmake nsis wine automake texlive texlive-plain-generic texlive-xetex rsync p7zip-full g++ gettext python3 tcl pandoc po4a bsdutils
      - name: configure compiler
        run: |
             sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
             sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
      - name: checkout maxima
        run: |
             git clone https://git.code.sf.net/p/maxima/code maxima-code
      - name: configure
        run: |
             mkdir maxima-code/crosscompile-windows/build
             cd maxima-code/crosscompile-windows/build
             cmake -DBUILD_64BIT=NO ..
      - name: compile tcl
        run: |
             cd maxima-code/crosscompile-windows/build
             cmake ..
             make tcl
      - name: compile tk
        run: |
             cd maxima-code/crosscompile-windows/build
             make tk
      - name: compile clisp
        run: |
             cd maxima-code/crosscompile-windows/build
             make clisp
      - name: compile sbcl
        run: |
             cd maxima-code/crosscompile-windows/build
             make sbcl
      - name: compile gnuplot
        run: |
             cd maxima-code/crosscompile-windows/build
             make gnuplot
      - name: compile vtk
        run: |
             cd maxima-code/crosscompile-windows/build
             make vtk
      - name: compile texinfo
        run: |
             cd maxima-code/crosscompile-windows/build
             make texinfo
      - name: compile maxima
        run: |
             cd maxima-code/crosscompile-windows/build
             script -qc /bin/bash -c "make maxima"
      - name: compile wxWidgets
        run: |
             cd maxima-code/crosscompile-windows/build
             make wxwidgets
      - name: compile wxMaxima
        run: |
             cd maxima-code/crosscompile-windows/build
             make wxmaxima
      - name: create package
        run: |
             cd maxima-code/crosscompile-windows/build
             make package
